AssignRoleDynamically/AuthenticationAndAuthorizationEg/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AuthenticationAndAuthorizationEg.Controllers
{
    public class AboutUsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AssignRoleDynamically/AuthenticationAndAuthorizationEg/Controllers/AccountManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AuthenticationAndAuthorizationEg.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AuthenticationAndAuthorizationEg.Controllers
{
    [Authorize(Roles ="Admin")]
    public class AccountManagerController : Controller
    {
        UserManager<IdentityUser> userManager;
        RoleManager<IdentityRole> roleManager;

        public AccountManagerController(UserManager<IdentityUser> _userManager, RoleManager<IdentityRole> _roleManager)
        {
            userManager = _userManager;
            roleManager = _roleManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AssignRole()
        {
            var users = userManager.Users.ToList();
            var roles = roleManager.Roles.ToList();

            List<string> listRoles = new List<string>();
            foreach (var item in roles)
            {
                listRoles.Add(item.Name);
            }

            List<AssignRoleViewModel> list = new List<AssignRoleViewModel>();

            foreach (var item in users)
            {
                AssignRoleViewModel model = new AssignRoleViewModel();
                model.UserId = item.Id;
                model.UserName = item.UserName;
                model.Email = item.Email;
                model.RoleName = userManager.GetRolesAsync(item).Result.Count != 0 ? userManager.GetRolesAsync(item).Result[0] : "";
                model.Roles = listRoles;
                list.Add(model);
            }

            return View(list);
        }

        [HttpPost]
        public async Task<IActionResult> AssignRole(string UserId,string RoleName)
        {
                var user = userManager.FindByIdAsync(UserId).Result;

                var roles = roleManager.Roles.ToList();

                List<string> listRoles = new List<string>();
                foreach (var item in roles)
                {
                    listRoles.Add(item.Name);
                }
                var Result1 = await userManager.RemoveFromRolesAsync(user, listRoles);

                var Result = await userManager.AddToRoleAsync(user, RoleName);
                return RedirectToAction("AssignRole");
        }
    }
}

AssignRoleDynamically/AuthenticationAndAuthorizationEg/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AuthenticationAndAuthorizationEg.Controllers
{
    [Authorize]
    public class ServicesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AssignRoleDynamically/AuthenticationAndAuthorizationEg/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AuthenticationAndAuthorizationEg.Controllers
{
    
    public class StudentsController : Controller
    {
        [Authorize(Roles ="Admin,User")]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }
    }
}

AssignRoleDynamically/AuthenticationAndAuthorizationEg/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Layout</title>
</head>
<body>
    <header>
        <a asp-controller="Home" asp-action="Index">Home</a>
        <a asp-controller="AboutUs" asp-action="Index">AboutUs</a>
        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
        {
        <a asp-controller="AccountManager" asp-action="AssignRole">AssignRole</a>
        }
        @if (User.Identity.IsAuthenticated && (User.IsInRole("User") || User.IsInRole("Admin")))
        {
        <a asp-controller="Students" asp-action="Index">Students</a>
        }

        @if (!User.Identity.IsAuthenticated)
        {
        <a asp-controller="Account" asp-action="Register">Register</a>
        <a asp-controller="Account" asp-action="Login">Login</a>
        }
        else
        {
    <a asp-controller="Services" asp-action="Index">Services</a>
    <a asp-controller="Account" asp-action="Logout">Logout</a>
        }
        @if (User.Identity.IsAuthenticated)
        {
        <span>Welcome Mr./Ms.  @User.Identity.Name </span>
        }
    </header>
    <section>@RenderBody()</section>
    <footer>www.ManzoorTheTrainer.com</footer>
</body>
</html>